export const IS_AUTHORIZATION = 'authorization/IS_AUTHORIZATION'
export const IS_FETCHING_CHECK_AUTH = 'authorization/IS_FETCHING_CHECK_AUTH'
export const SET_AUTH_ERROR = 'authorization/SET_AUTH_ERROR'
export const LOG_OUT = 'authorization/LOG_OUT'
export const SET_AUTH_ROLE = 'authorization/SET_AUTH_ROLE'
export const APP_AUTHORIZATION = 'authorization/APP_AUTHORIZATION'
export const AUTH_FETCH_STATUS = 'authorization/AUTH_FETCH_STATUS'